// CSOH Website - Interactive JavaScript

// Debounce function for performance optimization
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// Cache frequently accessed DOM elements
const domCache = {
    searchInput: null,
    categoryHeaders: null,
    cards: null
};

function sanitize(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

document.addEventListener('DOMContentLoaded', function() {
    document.body.classList.add('js-enabled');
    
    // Initialize DOM cache
    domCache.searchInput = document.getElementById('searchInput');
    domCache.categoryHeaders = document.querySelectorAll('.category-section h3');
    domCache.cards = document.querySelectorAll('.resource-card');

    // Enforce rel attributes on external links opened in new tabs.
    document.querySelectorAll('a[target="_blank"]').forEach(link => {
        const rel = (link.getAttribute('rel') || '').split(' ').filter(Boolean);
        if (!rel.includes('noopener')) rel.push('noopener');
        if (!rel.includes('noreferrer')) rel.push('noreferrer');
        link.setAttribute('rel', rel.join(' '));
    });

    // Hamburger menu toggle
    const hamburger = document.querySelector('.hamburger');
    if (hamburger) {
        hamburger.addEventListener('click', function() {
            const header = this.closest('.header-content');
            const isOpen = header.classList.toggle('nav-open');
            this.setAttribute('aria-expanded', String(isOpen));
            this.textContent = isOpen ? '✕' : '☰';
        });
    }

    // Add accessible label for search input
    if (domCache.searchInput && !document.querySelector('label[for="searchInput"]')) {
        const label = document.createElement('label');
        label.setAttribute('for', 'searchInput');
        label.className = 'visually-hidden';
        label.textContent = 'Search resources';
        domCache.searchInput.parentNode.insertBefore(label, domCache.searchInput);
    }
    
    // Add icons to resource cards
    addIconsToCards();

    // Load preview mapping (generated by tools/generate_previews.py) then add previews
    loadPreviewMap().then(() => {
        addPreviewImagesToCards();
    });
    
    // Show All Articles button
    const showAllBtn = document.getElementById('showAllBtn');
    if (showAllBtn) {
        showAllBtn.addEventListener('click', () => {
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            // Remove active state from all tag filters
            document.querySelectorAll('.filter-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            // Show all cards
            const cards = document.querySelectorAll('.resource-card');
            cards.forEach(card => {
                getToggleTarget(card).style.display = '';
            });
            updateVisibleCount();
        });
    }

    // Search functionality with debounce for better performance
    if (domCache.searchInput) {
        const params = new URLSearchParams(window.location.search);
        const query = sanitize(params.get('q') || '');
        if (query) {
            domCache.searchInput.value = query;
            filterResources(query.toLowerCase());
        }

        const debouncedSearch = debounce(function(e) {
            const searchTerm = e.target.value.toLowerCase();
            filterResources(searchTerm);
        }, 150);
        domCache.searchInput.addEventListener('input', debouncedSearch);
    }

    // Category filter buttons - direct attachment for better mobile support
    const categoryButtons = document.querySelectorAll('button[data-category]:not(.tag-filter)');
    categoryButtons.forEach(btn => {
        btn.addEventListener('click', function(e) {
            e.preventDefault();
            const category = this.dataset.category;
            
            // Remove active class from all category buttons
            document.querySelectorAll('button[data-category]:not(.tag-filter)').forEach(b => {
                b.classList.remove('active');
                b.setAttribute('aria-pressed', 'false');
            });
            
            // Add active class to clicked button
            this.classList.add('active');
            this.setAttribute('aria-pressed', 'true');
            
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            
            // Filter by category
            if (category === 'all') {
                // Show all cards
                const cards = document.querySelectorAll('.resource-card');
                cards.forEach(card => {
                    getToggleTarget(card).style.display = '';
                });
            } else if (category === 'new') {
                // Filter by 'new' tag
                filterByTagText('new');
            } else {
                // Filter by category tag (ctf, tool, certification, lab, ai-security, job)
                filterByTagText(category);
            }
            
            updateVisibleCount();
        });
    });

    // Category collapse/expand - use event delegation
    const mainContent = document.getElementById('main-content');
    if (mainContent) {
        // Initialize ARIA attributes on category headers
        document.querySelectorAll('.category-section h3').forEach(header => {
            header.setAttribute('role', 'button');
            header.setAttribute('tabindex', '0');
            const isCollapsed = header.parentElement.classList.contains('collapsed');
            header.setAttribute('aria-expanded', String(!isCollapsed));
        });

        mainContent.addEventListener('click', function(e) {
            const header = e.target.closest('.category-section h3');
            if (header && header.parentElement.classList.contains('category-section')) {
                header.parentElement.classList.toggle('collapsed');
                const isCollapsed = header.parentElement.classList.contains('collapsed');
                header.setAttribute('aria-expanded', String(!isCollapsed));
            }
        });

        // Keyboard support: Enter/Space to toggle
        mainContent.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' || e.key === ' ') {
                const header = e.target.closest('.category-section h3');
                if (header && header.parentElement.classList.contains('category-section')) {
                    e.preventDefault();
                    header.click();
                }
            }
        });
    }

    // Card click functionality is now handled via HTML <a> wrapper

    // Smooth scrolling for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
    // Initialize dynamic tag filters and visible count on load
    if (typeof generateTagFilters === 'function') generateTagFilters();
    if (typeof updateVisibleCount === 'function') updateVisibleCount();
});

// Generate tag filter buttons dynamically from tags on the page
function generateTagFilters() {
    const container = document.getElementById('allTagsContainer');
    if (!container) return;
    container.innerHTML = '';

    // Count occurrences of each tag text
    const tagNodes = Array.from(document.querySelectorAll('.resource-card .tag'));
    const counts = {};
    tagNodes.forEach(t => {
        const txt = t.textContent.trim();
        if (!txt) return;
        counts[txt] = (counts[txt] || 0) + 1;
    });

    // Sort tags by frequency (descending), tiebreak alphabetically
    const sortedTags = Object.keys(counts).sort((a, b) => {
        const diff = counts[b] - counts[a];
        return diff !== 0 ? diff : a.localeCompare(b);
    });

    // Track expanded state
    let isExpanded = false;
    const TOP_N = 20;

    // Function to render tags (top N or all)
    const renderTags = (showAll = false) => {
        // Clear existing buttons but keep toggle button if visible
        Array.from(container.querySelectorAll('.tag-filter')).forEach(btn => btn.remove());
        Array.from(container.querySelectorAll('.toggle-tags-btn')).forEach(btn => btn.remove());

        const tagsToRender = showAll ? sortedTags : sortedTags.slice(0, TOP_N);

        tagsToRender.forEach(tagText => {
            const btn = document.createElement('button');
            btn.className = 'filter-btn tag-filter';
            btn.dataset.tag = tagText;
            btn.textContent = `${tagText} (${counts[tagText]})`;
            btn.title = `${counts[tagText]} resources`;
            btn.addEventListener('click', function() {
                // clear other active buttons
                document.querySelectorAll('.filter-btn').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                document.querySelectorAll('.tag-filter').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                this.classList.add('active');
                this.setAttribute('aria-pressed', 'true');
                filterByTagText(tagText);
            });
            container.appendChild(btn);
        });

        // Add toggle button if there are more tags than TOP_N
        if (sortedTags.length > TOP_N) {
            const toggleBtn = document.createElement('button');
            toggleBtn.className = 'filter-btn toggle-tags-btn';
            toggleBtn.textContent = showAll ? `Show fewer tags (${TOP_N})` : `Show all tags (${sortedTags.length})`;
            toggleBtn.addEventListener('click', function() {
                isExpanded = !isExpanded;
                renderTags(isExpanded);
            });
            container.appendChild(toggleBtn);
        }
    };

    // Initial render: top N tags only
    renderTags(false);
}

let previewMap = {};

function loadPreviewMap() {
    return fetch('preview-mapping.json')
        .then(resp => {
            if (!resp.ok) return {};
            return resp.json();
        })
        .then(json => {
            previewMap = json || {};
        })
        .catch(() => { previewMap = {}; });
}

// Filter cards by tag text (case-insensitive)
function filterByTagText(tagText) {
    const search = tagText.toLowerCase();
    const cards = document.querySelectorAll('.resource-card');
    cards.forEach(card => {
        const tags = Array.from(card.querySelectorAll('.tag')).map(t => t.textContent.toLowerCase()).join(' ');
        getToggleTarget(card).style.display = tags.includes(search) ? '' : 'none';
    });
    updateVisibleCount();
}

function addIconsToCards() {
    const cards = document.querySelectorAll('.resource-card');
    
    cards.forEach(card => {
        // Check if icon already exists
        if (card.querySelector('.resource-card-icon')) return;
        
        const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase());
        const title = card.querySelector('h3').textContent.toLowerCase();
        
        let icon = '🔐'; // default security icon
        let iconClass = '';
        
        // Determine icon based on tags and content
        if (tags.some(tag => tag.includes('ctf')) || title.includes('ctf') || title.includes('goat') || title.includes('vulnerable')) {
            icon = '🎯';
            iconClass = 'ctf';
        } else if (tags.some(tag => tag.includes('tool')) || tags.some(tag => tag.includes('cspm')) || tags.some(tag => tag.includes('cnapp'))) {
            icon = '🛠️';
            iconClass = 'tool';
        } else if (tags.some(tag => tag.includes('certification')) || title.includes('cert')) {
            icon = '🎓';
            iconClass = 'certification';
        } else if (tags.some(tag => tag.includes('lab') || tag.includes('hands-on') || tag.includes('training'))) {
            icon = '🧪';
            iconClass = 'lab';
        } else if (tags.some(tag => tag.includes('kubernetes') || tag.includes('k8s')) || title.includes('kubernetes')) {
            icon = '☸️';
            iconClass = 'kubernetes';
        } else if (tags.some(tag => tag.includes('ai') || tag.includes('ml')) || title.includes('ai')) {
            icon = '🤖';
            iconClass = 'ai';
        } else if (title.includes('aws')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('azure')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('gcp') || title.includes('google cloud')) {
            icon = '☁️';
            iconClass = 'tool';
        }
        
        // Create icon element
        const iconDiv = document.createElement('div');
        iconDiv.className = `resource-card-icon ${iconClass}`;
        iconDiv.textContent = icon;
        
        // Insert icon at the beginning of the card
        card.insertBefore(iconDiv, card.firstChild);
    });
}

// Insert a small preview screenshot for each resource card.
// Uses WordPress mShots service to generate a lightweight thumbnail.
function addPreviewImagesToCards() {
    const cards = document.querySelectorAll('.resource-card');

    cards.forEach(card => {
        // Skip if card marked as no-preview (e.g., index page category cards)
        if (card.hasAttribute('data-no-preview')) return;
        
        // avoid duplicating previews
        if (card.querySelector('.resource-preview')) return;

        const link = card.querySelector('h3 a');
        if (!link) return;

        const url = link.href;
        if (!url) return;

        const img = document.createElement('img');
        img.className = 'resource-preview';
        img.alt = `Preview of ${link.textContent.trim()}`;
        img.loading = 'lazy';
        img.referrerPolicy = 'no-referrer';
        img.decoding = 'async';
        // Set explicit dimensions to prevent layout shift
        img.width = 600;
        img.height = 160;


        // Use local preview when available; otherwise fall back to remote mShots.
        if (previewMap[url]) {
            img.src = previewMap[url];
            img.onerror = function() { img.remove(); };
        } else {
            // fallback to mShots for sites without local previews
            img.src = `https://s.wordpress.com/mshots/v1/${encodeURIComponent(url)}?w=600`;
            // remove the image if it fails to load or appears to be a tiny placeholder
            img.onerror = function() { img.remove(); };
            img.onload = function() {
                try {
                    if ((img.naturalWidth && img.naturalWidth < 50) || (img.naturalHeight && img.naturalHeight < 50)) {
                        img.remove();
                    }
                } catch (e) {
                    // ignore
                }
            };
        }

        // Place the preview after any icon but before the title
        const icon = card.querySelector('.resource-card-icon');
        if (icon && icon.nextSibling) {
            card.insertBefore(img, icon.nextSibling);
        } else if (icon) {
            card.appendChild(img);
        } else {
            card.insertBefore(img, card.firstChild);
        }
    });
}

// Helper: get the element to show/hide for a given card.
// On news.html cards are wrapped in <a class="card-link">, on resources.html they are standalone.
function getToggleTarget(card) {
    const parent = card.parentElement;
    return (parent && parent.classList.contains('card-link')) ? parent : card;
}

function filterResources(searchTerm) {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    
    // Use requestAnimationFrame for smoother rendering
    requestAnimationFrame(() => {
        cards.forEach(card => {
            const title = card.querySelector('h3')?.textContent.toLowerCase() || '';
            const paragraphs = Array.from(card.querySelectorAll('p')).map(p => p.textContent).join(' ').toLowerCase();
            const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase()).join(' ');

            const matches = title.includes(searchTerm) ||
                           paragraphs.includes(searchTerm) ||
                           tags.includes(searchTerm);

            getToggleTarget(card).style.display = matches ? '' : 'none';
        });

        updateVisibleCount();
    });
}

function updateVisibleCount() {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    let visibleCount = 0;
    
    cards.forEach(card => {
        if (getToggleTarget(card).style.display !== 'none') {
            visibleCount++;
        }
    });
    
    const countElement = document.getElementById('visibleCount');
    if (countElement) {
        countElement.textContent = visibleCount;
    }
}


